/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedApiDocsRouteRouteImport } from './routes/_authenticated/api-docs/route'
import { Route as AuthenticatedWebhooksIndexRouteImport } from './routes/_authenticated/webhooks/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSystemIndexRouteImport } from './routes/_authenticated/system/index'
import { Route as AuthenticatedSkillsIndexRouteImport } from './routes/_authenticated/skills/index'
import { Route as AuthenticatedSkillStoreIndexRouteImport } from './routes/_authenticated/skill-store/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSessionsIndexRouteImport } from './routes/_authenticated/sessions/index'
import { Route as AuthenticatedRuntimesIndexRouteImport } from './routes/_authenticated/runtimes/index'
import { Route as AuthenticatedProvidersIndexRouteImport } from './routes/_authenticated/providers/index'
import { Route as AuthenticatedMonitoringIndexRouteImport } from './routes/_authenticated/monitoring/index'
import { Route as AuthenticatedMcpServersIndexRouteImport } from './routes/_authenticated/mcp-servers/index'
import { Route as AuthenticatedImagesIndexRouteImport } from './routes/_authenticated/images/index'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated/history/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedFilesIndexRouteImport } from './routes/_authenticated/files/index'
import { Route as AuthenticatedDemoIndexRouteImport } from './routes/_authenticated/demo/index'
import { Route as AuthenticatedCommandCenterIndexRouteImport } from './routes/_authenticated/command-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedBatchesIndexRouteImport } from './routes/_authenticated/batches/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedApiPlaygroundIndexRouteImport } from './routes/_authenticated/api-playground/index'
import { Route as AuthenticatedApiKeysIndexRouteImport } from './routes/_authenticated/api-keys/index'
import { Route as AuthenticatedApiDocsIndexRouteImport } from './routes/_authenticated/api-docs/index'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents/index'
import { Route as AuthenticatedTasksIdRouteImport } from './routes/_authenticated/tasks/$id'
import { Route as AuthenticatedSkillsNewRouteImport } from './routes/_authenticated/skills/new'
import { Route as AuthenticatedSkillsIdRouteImport } from './routes/_authenticated/skills/$id'
import { Route as AuthenticatedSessionsIdRouteImport } from './routes/_authenticated/sessions/$id'
import { Route as AuthenticatedMcpServersNewRouteImport } from './routes/_authenticated/mcp-servers/new'
import { Route as AuthenticatedMcpServersIdRouteImport } from './routes/_authenticated/mcp-servers/$id'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedBatchesBatchIdRouteImport } from './routes/_authenticated/batches/$batchId'
import { Route as AuthenticatedApiDocsUploadFileRouteImport } from './routes/_authenticated/api-docs/upload-file'
import { Route as AuthenticatedApiDocsStreamEventsRouteImport } from './routes/_authenticated/api-docs/stream-events'
import { Route as AuthenticatedApiDocsStreamBatchEventsRouteImport } from './routes/_authenticated/api-docs/stream-batch-events'
import { Route as AuthenticatedApiDocsStartBatchRouteImport } from './routes/_authenticated/api-docs/start-batch'
import { Route as AuthenticatedApiDocsPauseBatchRouteImport } from './routes/_authenticated/api-docs/pause-batch'
import { Route as AuthenticatedApiDocsLoginRouteImport } from './routes/_authenticated/api-docs/login'
import { Route as AuthenticatedApiDocsListWebhooksRouteImport } from './routes/_authenticated/api-docs/list-webhooks'
import { Route as AuthenticatedApiDocsListFilesRouteImport } from './routes/_authenticated/api-docs/list-files'
import { Route as AuthenticatedApiDocsListBatchesRouteImport } from './routes/_authenticated/api-docs/list-batches'
import { Route as AuthenticatedApiDocsListBatchTasksRouteImport } from './routes/_authenticated/api-docs/list-batch-tasks'
import { Route as AuthenticatedApiDocsGetWebhookRouteImport } from './routes/_authenticated/api-docs/get-webhook'
import { Route as AuthenticatedApiDocsGetTasksRouteImport } from './routes/_authenticated/api-docs/get-tasks'
import { Route as AuthenticatedApiDocsGetTaskRouteImport } from './routes/_authenticated/api-docs/get-task'
import { Route as AuthenticatedApiDocsGetFileRouteImport } from './routes/_authenticated/api-docs/get-file'
import { Route as AuthenticatedApiDocsGetBatchRouteImport } from './routes/_authenticated/api-docs/get-batch'
import { Route as AuthenticatedApiDocsDownloadFileRouteImport } from './routes/_authenticated/api-docs/download-file'
import { Route as AuthenticatedApiDocsDeleteWebhookRouteImport } from './routes/_authenticated/api-docs/delete-webhook'
import { Route as AuthenticatedApiDocsDeleteFileRouteImport } from './routes/_authenticated/api-docs/delete-file'
import { Route as AuthenticatedApiDocsDeleteBatchRouteImport } from './routes/_authenticated/api-docs/delete-batch'
import { Route as AuthenticatedApiDocsDeleteApiKeyRouteImport } from './routes/_authenticated/api-docs/delete-api-key'
import { Route as AuthenticatedApiDocsCreateWebhookRouteImport } from './routes/_authenticated/api-docs/create-webhook'
import { Route as AuthenticatedApiDocsCreateTaskRouteImport } from './routes/_authenticated/api-docs/create-task'
import { Route as AuthenticatedApiDocsCreateBatchRouteImport } from './routes/_authenticated/api-docs/create-batch'
import { Route as AuthenticatedApiDocsCreateApiKeyRouteImport } from './routes/_authenticated/api-docs/create-api-key'
import { Route as AuthenticatedApiDocsCancelTaskRouteImport } from './routes/_authenticated/api-docs/cancel-task'
import { Route as AuthenticatedApiDocsCancelBatchRouteImport } from './routes/_authenticated/api-docs/cancel-batch'
import { Route as AuthenticatedApiDocsApiKeysRouteImport } from './routes/_authenticated/api-docs/api-keys'
import { Route as AuthenticatedAgentsNewRouteImport } from './routes/_authenticated/agents/new'
import { Route as AuthenticatedAgentsIdRouteImport } from './routes/_authenticated/agents/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApiDocsRouteRoute =
  AuthenticatedApiDocsRouteRouteImport.update({
    id: '/api-docs',
    path: '/api-docs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebhooksIndexRoute =
  AuthenticatedWebhooksIndexRouteImport.update({
    id: '/webhooks/',
    path: '/webhooks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemIndexRoute =
  AuthenticatedSystemIndexRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSkillsIndexRoute =
  AuthenticatedSkillsIndexRouteImport.update({
    id: '/skills/',
    path: '/skills/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSkillStoreIndexRoute =
  AuthenticatedSkillStoreIndexRouteImport.update({
    id: '/skill-store/',
    path: '/skill-store/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsIndexRoute =
  AuthenticatedSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRuntimesIndexRoute =
  AuthenticatedRuntimesIndexRouteImport.update({
    id: '/runtimes/',
    path: '/runtimes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProvidersIndexRoute =
  AuthenticatedProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitoringIndexRoute =
  AuthenticatedMonitoringIndexRouteImport.update({
    id: '/monitoring/',
    path: '/monitoring/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMcpServersIndexRoute =
  AuthenticatedMcpServersIndexRouteImport.update({
    id: '/mcp-servers/',
    path: '/mcp-servers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImagesIndexRoute =
  AuthenticatedImagesIndexRouteImport.update({
    id: '/images/',
    path: '/images/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFilesIndexRoute = AuthenticatedFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemoIndexRoute = AuthenticatedDemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandCenterIndexRoute =
  AuthenticatedCommandCenterIndexRouteImport.update({
    id: '/command-center/',
    path: '/command-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBatchesIndexRoute =
  AuthenticatedBatchesIndexRouteImport.update({
    id: '/batches/',
    path: '/batches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiPlaygroundIndexRoute =
  AuthenticatedApiPlaygroundIndexRouteImport.update({
    id: '/api-playground/',
    path: '/api-playground/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiKeysIndexRoute =
  AuthenticatedApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiDocsIndexRoute =
  AuthenticatedApiDocsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIdRoute = AuthenticatedTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsNewRoute = AuthenticatedSkillsNewRouteImport.update({
  id: '/skills/new',
  path: '/skills/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsIdRoute = AuthenticatedSkillsIdRouteImport.update({
  id: '/skills/$id',
  path: '/skills/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsIdRoute = AuthenticatedSessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMcpServersNewRoute =
  AuthenticatedMcpServersNewRouteImport.update({
    id: '/mcp-servers/new',
    path: '/mcp-servers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMcpServersIdRoute =
  AuthenticatedMcpServersIdRouteImport.update({
    id: '/mcp-servers/$id',
    path: '/mcp-servers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBatchesBatchIdRoute =
  AuthenticatedBatchesBatchIdRouteImport.update({
    id: '/batches/$batchId',
    path: '/batches/$batchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiDocsUploadFileRoute =
  AuthenticatedApiDocsUploadFileRouteImport.update({
    id: '/upload-file',
    path: '/upload-file',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsStreamEventsRoute =
  AuthenticatedApiDocsStreamEventsRouteImport.update({
    id: '/stream-events',
    path: '/stream-events',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsStreamBatchEventsRoute =
  AuthenticatedApiDocsStreamBatchEventsRouteImport.update({
    id: '/stream-batch-events',
    path: '/stream-batch-events',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsStartBatchRoute =
  AuthenticatedApiDocsStartBatchRouteImport.update({
    id: '/start-batch',
    path: '/start-batch',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsPauseBatchRoute =
  AuthenticatedApiDocsPauseBatchRouteImport.update({
    id: '/pause-batch',
    path: '/pause-batch',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsLoginRoute =
  AuthenticatedApiDocsLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsListWebhooksRoute =
  AuthenticatedApiDocsListWebhooksRouteImport.update({
    id: '/list-webhooks',
    path: '/list-webhooks',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsListFilesRoute =
  AuthenticatedApiDocsListFilesRouteImport.update({
    id: '/list-files',
    path: '/list-files',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsListBatchesRoute =
  AuthenticatedApiDocsListBatchesRouteImport.update({
    id: '/list-batches',
    path: '/list-batches',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsListBatchTasksRoute =
  AuthenticatedApiDocsListBatchTasksRouteImport.update({
    id: '/list-batch-tasks',
    path: '/list-batch-tasks',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsGetWebhookRoute =
  AuthenticatedApiDocsGetWebhookRouteImport.update({
    id: '/get-webhook',
    path: '/get-webhook',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsGetTasksRoute =
  AuthenticatedApiDocsGetTasksRouteImport.update({
    id: '/get-tasks',
    path: '/get-tasks',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsGetTaskRoute =
  AuthenticatedApiDocsGetTaskRouteImport.update({
    id: '/get-task',
    path: '/get-task',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsGetFileRoute =
  AuthenticatedApiDocsGetFileRouteImport.update({
    id: '/get-file',
    path: '/get-file',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsGetBatchRoute =
  AuthenticatedApiDocsGetBatchRouteImport.update({
    id: '/get-batch',
    path: '/get-batch',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsDownloadFileRoute =
  AuthenticatedApiDocsDownloadFileRouteImport.update({
    id: '/download-file',
    path: '/download-file',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsDeleteWebhookRoute =
  AuthenticatedApiDocsDeleteWebhookRouteImport.update({
    id: '/delete-webhook',
    path: '/delete-webhook',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsDeleteFileRoute =
  AuthenticatedApiDocsDeleteFileRouteImport.update({
    id: '/delete-file',
    path: '/delete-file',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsDeleteBatchRoute =
  AuthenticatedApiDocsDeleteBatchRouteImport.update({
    id: '/delete-batch',
    path: '/delete-batch',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsDeleteApiKeyRoute =
  AuthenticatedApiDocsDeleteApiKeyRouteImport.update({
    id: '/delete-api-key',
    path: '/delete-api-key',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsCreateWebhookRoute =
  AuthenticatedApiDocsCreateWebhookRouteImport.update({
    id: '/create-webhook',
    path: '/create-webhook',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsCreateTaskRoute =
  AuthenticatedApiDocsCreateTaskRouteImport.update({
    id: '/create-task',
    path: '/create-task',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsCreateBatchRoute =
  AuthenticatedApiDocsCreateBatchRouteImport.update({
    id: '/create-batch',
    path: '/create-batch',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsCreateApiKeyRoute =
  AuthenticatedApiDocsCreateApiKeyRouteImport.update({
    id: '/create-api-key',
    path: '/create-api-key',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsCancelTaskRoute =
  AuthenticatedApiDocsCancelTaskRouteImport.update({
    id: '/cancel-task',
    path: '/cancel-task',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsCancelBatchRoute =
  AuthenticatedApiDocsCancelBatchRouteImport.update({
    id: '/cancel-batch',
    path: '/cancel-batch',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedApiDocsApiKeysRoute =
  AuthenticatedApiDocsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedApiDocsRouteRoute,
  } as any)
const AuthenticatedAgentsNewRoute = AuthenticatedAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsIdRoute = AuthenticatedAgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/api-docs': typeof AuthenticatedApiDocsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/agents/$id': typeof AuthenticatedAgentsIdRoute
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/api-docs/api-keys': typeof AuthenticatedApiDocsApiKeysRoute
  '/api-docs/cancel-batch': typeof AuthenticatedApiDocsCancelBatchRoute
  '/api-docs/cancel-task': typeof AuthenticatedApiDocsCancelTaskRoute
  '/api-docs/create-api-key': typeof AuthenticatedApiDocsCreateApiKeyRoute
  '/api-docs/create-batch': typeof AuthenticatedApiDocsCreateBatchRoute
  '/api-docs/create-task': typeof AuthenticatedApiDocsCreateTaskRoute
  '/api-docs/create-webhook': typeof AuthenticatedApiDocsCreateWebhookRoute
  '/api-docs/delete-api-key': typeof AuthenticatedApiDocsDeleteApiKeyRoute
  '/api-docs/delete-batch': typeof AuthenticatedApiDocsDeleteBatchRoute
  '/api-docs/delete-file': typeof AuthenticatedApiDocsDeleteFileRoute
  '/api-docs/delete-webhook': typeof AuthenticatedApiDocsDeleteWebhookRoute
  '/api-docs/download-file': typeof AuthenticatedApiDocsDownloadFileRoute
  '/api-docs/get-batch': typeof AuthenticatedApiDocsGetBatchRoute
  '/api-docs/get-file': typeof AuthenticatedApiDocsGetFileRoute
  '/api-docs/get-task': typeof AuthenticatedApiDocsGetTaskRoute
  '/api-docs/get-tasks': typeof AuthenticatedApiDocsGetTasksRoute
  '/api-docs/get-webhook': typeof AuthenticatedApiDocsGetWebhookRoute
  '/api-docs/list-batch-tasks': typeof AuthenticatedApiDocsListBatchTasksRoute
  '/api-docs/list-batches': typeof AuthenticatedApiDocsListBatchesRoute
  '/api-docs/list-files': typeof AuthenticatedApiDocsListFilesRoute
  '/api-docs/list-webhooks': typeof AuthenticatedApiDocsListWebhooksRoute
  '/api-docs/login': typeof AuthenticatedApiDocsLoginRoute
  '/api-docs/pause-batch': typeof AuthenticatedApiDocsPauseBatchRoute
  '/api-docs/start-batch': typeof AuthenticatedApiDocsStartBatchRoute
  '/api-docs/stream-batch-events': typeof AuthenticatedApiDocsStreamBatchEventsRoute
  '/api-docs/stream-events': typeof AuthenticatedApiDocsStreamEventsRoute
  '/api-docs/upload-file': typeof AuthenticatedApiDocsUploadFileRoute
  '/batches/$batchId': typeof AuthenticatedBatchesBatchIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/mcp-servers/$id': typeof AuthenticatedMcpServersIdRoute
  '/mcp-servers/new': typeof AuthenticatedMcpServersNewRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/skills/$id': typeof AuthenticatedSkillsIdRoute
  '/skills/new': typeof AuthenticatedSkillsNewRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/api-docs/': typeof AuthenticatedApiDocsIndexRoute
  '/api-keys': typeof AuthenticatedApiKeysIndexRoute
  '/api-playground': typeof AuthenticatedApiPlaygroundIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/batches': typeof AuthenticatedBatchesIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/command-center': typeof AuthenticatedCommandCenterIndexRoute
  '/demo': typeof AuthenticatedDemoIndexRoute
  '/files': typeof AuthenticatedFilesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
  '/images': typeof AuthenticatedImagesIndexRoute
  '/mcp-servers': typeof AuthenticatedMcpServersIndexRoute
  '/monitoring': typeof AuthenticatedMonitoringIndexRoute
  '/providers': typeof AuthenticatedProvidersIndexRoute
  '/runtimes': typeof AuthenticatedRuntimesIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/skill-store': typeof AuthenticatedSkillStoreIndexRoute
  '/skills': typeof AuthenticatedSkillsIndexRoute
  '/system': typeof AuthenticatedSystemIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/webhooks': typeof AuthenticatedWebhooksIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/agents/$id': typeof AuthenticatedAgentsIdRoute
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/api-docs/api-keys': typeof AuthenticatedApiDocsApiKeysRoute
  '/api-docs/cancel-batch': typeof AuthenticatedApiDocsCancelBatchRoute
  '/api-docs/cancel-task': typeof AuthenticatedApiDocsCancelTaskRoute
  '/api-docs/create-api-key': typeof AuthenticatedApiDocsCreateApiKeyRoute
  '/api-docs/create-batch': typeof AuthenticatedApiDocsCreateBatchRoute
  '/api-docs/create-task': typeof AuthenticatedApiDocsCreateTaskRoute
  '/api-docs/create-webhook': typeof AuthenticatedApiDocsCreateWebhookRoute
  '/api-docs/delete-api-key': typeof AuthenticatedApiDocsDeleteApiKeyRoute
  '/api-docs/delete-batch': typeof AuthenticatedApiDocsDeleteBatchRoute
  '/api-docs/delete-file': typeof AuthenticatedApiDocsDeleteFileRoute
  '/api-docs/delete-webhook': typeof AuthenticatedApiDocsDeleteWebhookRoute
  '/api-docs/download-file': typeof AuthenticatedApiDocsDownloadFileRoute
  '/api-docs/get-batch': typeof AuthenticatedApiDocsGetBatchRoute
  '/api-docs/get-file': typeof AuthenticatedApiDocsGetFileRoute
  '/api-docs/get-task': typeof AuthenticatedApiDocsGetTaskRoute
  '/api-docs/get-tasks': typeof AuthenticatedApiDocsGetTasksRoute
  '/api-docs/get-webhook': typeof AuthenticatedApiDocsGetWebhookRoute
  '/api-docs/list-batch-tasks': typeof AuthenticatedApiDocsListBatchTasksRoute
  '/api-docs/list-batches': typeof AuthenticatedApiDocsListBatchesRoute
  '/api-docs/list-files': typeof AuthenticatedApiDocsListFilesRoute
  '/api-docs/list-webhooks': typeof AuthenticatedApiDocsListWebhooksRoute
  '/api-docs/login': typeof AuthenticatedApiDocsLoginRoute
  '/api-docs/pause-batch': typeof AuthenticatedApiDocsPauseBatchRoute
  '/api-docs/start-batch': typeof AuthenticatedApiDocsStartBatchRoute
  '/api-docs/stream-batch-events': typeof AuthenticatedApiDocsStreamBatchEventsRoute
  '/api-docs/stream-events': typeof AuthenticatedApiDocsStreamEventsRoute
  '/api-docs/upload-file': typeof AuthenticatedApiDocsUploadFileRoute
  '/batches/$batchId': typeof AuthenticatedBatchesBatchIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/mcp-servers/$id': typeof AuthenticatedMcpServersIdRoute
  '/mcp-servers/new': typeof AuthenticatedMcpServersNewRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/skills/$id': typeof AuthenticatedSkillsIdRoute
  '/skills/new': typeof AuthenticatedSkillsNewRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/api-docs': typeof AuthenticatedApiDocsIndexRoute
  '/api-keys': typeof AuthenticatedApiKeysIndexRoute
  '/api-playground': typeof AuthenticatedApiPlaygroundIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/batches': typeof AuthenticatedBatchesIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/command-center': typeof AuthenticatedCommandCenterIndexRoute
  '/demo': typeof AuthenticatedDemoIndexRoute
  '/files': typeof AuthenticatedFilesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
  '/images': typeof AuthenticatedImagesIndexRoute
  '/mcp-servers': typeof AuthenticatedMcpServersIndexRoute
  '/monitoring': typeof AuthenticatedMonitoringIndexRoute
  '/providers': typeof AuthenticatedProvidersIndexRoute
  '/runtimes': typeof AuthenticatedRuntimesIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/skill-store': typeof AuthenticatedSkillStoreIndexRoute
  '/skills': typeof AuthenticatedSkillsIndexRoute
  '/system': typeof AuthenticatedSystemIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/webhooks': typeof AuthenticatedWebhooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/api-docs': typeof AuthenticatedApiDocsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/agents/$id': typeof AuthenticatedAgentsIdRoute
  '/_authenticated/agents/new': typeof AuthenticatedAgentsNewRoute
  '/_authenticated/api-docs/api-keys': typeof AuthenticatedApiDocsApiKeysRoute
  '/_authenticated/api-docs/cancel-batch': typeof AuthenticatedApiDocsCancelBatchRoute
  '/_authenticated/api-docs/cancel-task': typeof AuthenticatedApiDocsCancelTaskRoute
  '/_authenticated/api-docs/create-api-key': typeof AuthenticatedApiDocsCreateApiKeyRoute
  '/_authenticated/api-docs/create-batch': typeof AuthenticatedApiDocsCreateBatchRoute
  '/_authenticated/api-docs/create-task': typeof AuthenticatedApiDocsCreateTaskRoute
  '/_authenticated/api-docs/create-webhook': typeof AuthenticatedApiDocsCreateWebhookRoute
  '/_authenticated/api-docs/delete-api-key': typeof AuthenticatedApiDocsDeleteApiKeyRoute
  '/_authenticated/api-docs/delete-batch': typeof AuthenticatedApiDocsDeleteBatchRoute
  '/_authenticated/api-docs/delete-file': typeof AuthenticatedApiDocsDeleteFileRoute
  '/_authenticated/api-docs/delete-webhook': typeof AuthenticatedApiDocsDeleteWebhookRoute
  '/_authenticated/api-docs/download-file': typeof AuthenticatedApiDocsDownloadFileRoute
  '/_authenticated/api-docs/get-batch': typeof AuthenticatedApiDocsGetBatchRoute
  '/_authenticated/api-docs/get-file': typeof AuthenticatedApiDocsGetFileRoute
  '/_authenticated/api-docs/get-task': typeof AuthenticatedApiDocsGetTaskRoute
  '/_authenticated/api-docs/get-tasks': typeof AuthenticatedApiDocsGetTasksRoute
  '/_authenticated/api-docs/get-webhook': typeof AuthenticatedApiDocsGetWebhookRoute
  '/_authenticated/api-docs/list-batch-tasks': typeof AuthenticatedApiDocsListBatchTasksRoute
  '/_authenticated/api-docs/list-batches': typeof AuthenticatedApiDocsListBatchesRoute
  '/_authenticated/api-docs/list-files': typeof AuthenticatedApiDocsListFilesRoute
  '/_authenticated/api-docs/list-webhooks': typeof AuthenticatedApiDocsListWebhooksRoute
  '/_authenticated/api-docs/login': typeof AuthenticatedApiDocsLoginRoute
  '/_authenticated/api-docs/pause-batch': typeof AuthenticatedApiDocsPauseBatchRoute
  '/_authenticated/api-docs/start-batch': typeof AuthenticatedApiDocsStartBatchRoute
  '/_authenticated/api-docs/stream-batch-events': typeof AuthenticatedApiDocsStreamBatchEventsRoute
  '/_authenticated/api-docs/stream-events': typeof AuthenticatedApiDocsStreamEventsRoute
  '/_authenticated/api-docs/upload-file': typeof AuthenticatedApiDocsUploadFileRoute
  '/_authenticated/batches/$batchId': typeof AuthenticatedBatchesBatchIdRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/mcp-servers/$id': typeof AuthenticatedMcpServersIdRoute
  '/_authenticated/mcp-servers/new': typeof AuthenticatedMcpServersNewRoute
  '/_authenticated/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/_authenticated/skills/$id': typeof AuthenticatedSkillsIdRoute
  '/_authenticated/skills/new': typeof AuthenticatedSkillsNewRoute
  '/_authenticated/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/api-docs/': typeof AuthenticatedApiDocsIndexRoute
  '/_authenticated/api-keys/': typeof AuthenticatedApiKeysIndexRoute
  '/_authenticated/api-playground/': typeof AuthenticatedApiPlaygroundIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/batches/': typeof AuthenticatedBatchesIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/command-center/': typeof AuthenticatedCommandCenterIndexRoute
  '/_authenticated/demo/': typeof AuthenticatedDemoIndexRoute
  '/_authenticated/files/': typeof AuthenticatedFilesIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
  '/_authenticated/images/': typeof AuthenticatedImagesIndexRoute
  '/_authenticated/mcp-servers/': typeof AuthenticatedMcpServersIndexRoute
  '/_authenticated/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/_authenticated/providers/': typeof AuthenticatedProvidersIndexRoute
  '/_authenticated/runtimes/': typeof AuthenticatedRuntimesIndexRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/skill-store/': typeof AuthenticatedSkillStoreIndexRoute
  '/_authenticated/skills/': typeof AuthenticatedSkillsIndexRoute
  '/_authenticated/system/': typeof AuthenticatedSystemIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/webhooks/': typeof AuthenticatedWebhooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api-docs'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/agents/$id'
    | '/agents/new'
    | '/api-docs/api-keys'
    | '/api-docs/cancel-batch'
    | '/api-docs/cancel-task'
    | '/api-docs/create-api-key'
    | '/api-docs/create-batch'
    | '/api-docs/create-task'
    | '/api-docs/create-webhook'
    | '/api-docs/delete-api-key'
    | '/api-docs/delete-batch'
    | '/api-docs/delete-file'
    | '/api-docs/delete-webhook'
    | '/api-docs/download-file'
    | '/api-docs/get-batch'
    | '/api-docs/get-file'
    | '/api-docs/get-task'
    | '/api-docs/get-tasks'
    | '/api-docs/get-webhook'
    | '/api-docs/list-batch-tasks'
    | '/api-docs/list-batches'
    | '/api-docs/list-files'
    | '/api-docs/list-webhooks'
    | '/api-docs/login'
    | '/api-docs/pause-batch'
    | '/api-docs/start-batch'
    | '/api-docs/stream-batch-events'
    | '/api-docs/stream-events'
    | '/api-docs/upload-file'
    | '/batches/$batchId'
    | '/errors/$error'
    | '/mcp-servers/$id'
    | '/mcp-servers/new'
    | '/sessions/$id'
    | '/skills/$id'
    | '/skills/new'
    | '/tasks/$id'
    | '/agents'
    | '/api-docs/'
    | '/api-keys'
    | '/api-playground'
    | '/apps'
    | '/batches'
    | '/chats'
    | '/command-center'
    | '/demo'
    | '/files'
    | '/help-center'
    | '/history'
    | '/images'
    | '/mcp-servers'
    | '/monitoring'
    | '/providers'
    | '/runtimes'
    | '/sessions'
    | '/settings'
    | '/skill-store'
    | '/skills'
    | '/system'
    | '/tasks'
    | '/users'
    | '/webhooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/agents/$id'
    | '/agents/new'
    | '/api-docs/api-keys'
    | '/api-docs/cancel-batch'
    | '/api-docs/cancel-task'
    | '/api-docs/create-api-key'
    | '/api-docs/create-batch'
    | '/api-docs/create-task'
    | '/api-docs/create-webhook'
    | '/api-docs/delete-api-key'
    | '/api-docs/delete-batch'
    | '/api-docs/delete-file'
    | '/api-docs/delete-webhook'
    | '/api-docs/download-file'
    | '/api-docs/get-batch'
    | '/api-docs/get-file'
    | '/api-docs/get-task'
    | '/api-docs/get-tasks'
    | '/api-docs/get-webhook'
    | '/api-docs/list-batch-tasks'
    | '/api-docs/list-batches'
    | '/api-docs/list-files'
    | '/api-docs/list-webhooks'
    | '/api-docs/login'
    | '/api-docs/pause-batch'
    | '/api-docs/start-batch'
    | '/api-docs/stream-batch-events'
    | '/api-docs/stream-events'
    | '/api-docs/upload-file'
    | '/batches/$batchId'
    | '/errors/$error'
    | '/mcp-servers/$id'
    | '/mcp-servers/new'
    | '/sessions/$id'
    | '/skills/$id'
    | '/skills/new'
    | '/tasks/$id'
    | '/agents'
    | '/api-docs'
    | '/api-keys'
    | '/api-playground'
    | '/apps'
    | '/batches'
    | '/chats'
    | '/command-center'
    | '/demo'
    | '/files'
    | '/help-center'
    | '/history'
    | '/images'
    | '/mcp-servers'
    | '/monitoring'
    | '/providers'
    | '/runtimes'
    | '/sessions'
    | '/settings'
    | '/skill-store'
    | '/skills'
    | '/system'
    | '/tasks'
    | '/users'
    | '/webhooks'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/api-docs'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/agents/$id'
    | '/_authenticated/agents/new'
    | '/_authenticated/api-docs/api-keys'
    | '/_authenticated/api-docs/cancel-batch'
    | '/_authenticated/api-docs/cancel-task'
    | '/_authenticated/api-docs/create-api-key'
    | '/_authenticated/api-docs/create-batch'
    | '/_authenticated/api-docs/create-task'
    | '/_authenticated/api-docs/create-webhook'
    | '/_authenticated/api-docs/delete-api-key'
    | '/_authenticated/api-docs/delete-batch'
    | '/_authenticated/api-docs/delete-file'
    | '/_authenticated/api-docs/delete-webhook'
    | '/_authenticated/api-docs/download-file'
    | '/_authenticated/api-docs/get-batch'
    | '/_authenticated/api-docs/get-file'
    | '/_authenticated/api-docs/get-task'
    | '/_authenticated/api-docs/get-tasks'
    | '/_authenticated/api-docs/get-webhook'
    | '/_authenticated/api-docs/list-batch-tasks'
    | '/_authenticated/api-docs/list-batches'
    | '/_authenticated/api-docs/list-files'
    | '/_authenticated/api-docs/list-webhooks'
    | '/_authenticated/api-docs/login'
    | '/_authenticated/api-docs/pause-batch'
    | '/_authenticated/api-docs/start-batch'
    | '/_authenticated/api-docs/stream-batch-events'
    | '/_authenticated/api-docs/stream-events'
    | '/_authenticated/api-docs/upload-file'
    | '/_authenticated/batches/$batchId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/mcp-servers/$id'
    | '/_authenticated/mcp-servers/new'
    | '/_authenticated/sessions/$id'
    | '/_authenticated/skills/$id'
    | '/_authenticated/skills/new'
    | '/_authenticated/tasks/$id'
    | '/_authenticated/agents/'
    | '/_authenticated/api-docs/'
    | '/_authenticated/api-keys/'
    | '/_authenticated/api-playground/'
    | '/_authenticated/apps/'
    | '/_authenticated/batches/'
    | '/_authenticated/chats/'
    | '/_authenticated/command-center/'
    | '/_authenticated/demo/'
    | '/_authenticated/files/'
    | '/_authenticated/help-center/'
    | '/_authenticated/history/'
    | '/_authenticated/images/'
    | '/_authenticated/mcp-servers/'
    | '/_authenticated/monitoring/'
    | '/_authenticated/providers/'
    | '/_authenticated/runtimes/'
    | '/_authenticated/sessions/'
    | '/_authenticated/settings/'
    | '/_authenticated/skill-store/'
    | '/_authenticated/skills/'
    | '/_authenticated/system/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/webhooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/api-docs': {
      id: '/_authenticated/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof AuthenticatedApiDocsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhooks/': {
      id: '/_authenticated/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthenticatedWebhooksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/': {
      id: '/_authenticated/system/'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills/': {
      id: '/_authenticated/skills/'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skill-store/': {
      id: '/_authenticated/skill-store/'
      path: '/skill-store'
      fullPath: '/skill-store'
      preLoaderRoute: typeof AuthenticatedSkillStoreIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runtimes/': {
      id: '/_authenticated/runtimes/'
      path: '/runtimes'
      fullPath: '/runtimes'
      preLoaderRoute: typeof AuthenticatedRuntimesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/providers/': {
      id: '/_authenticated/providers/'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthenticatedProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring/': {
      id: '/_authenticated/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mcp-servers/': {
      id: '/_authenticated/mcp-servers/'
      path: '/mcp-servers'
      fullPath: '/mcp-servers'
      preLoaderRoute: typeof AuthenticatedMcpServersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/images/': {
      id: '/_authenticated/images/'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AuthenticatedImagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/files/': {
      id: '/_authenticated/files/'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/': {
      id: '/_authenticated/demo/'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthenticatedDemoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-center/': {
      id: '/_authenticated/command-center/'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batches/': {
      id: '/_authenticated/batches/'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof AuthenticatedBatchesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-playground/': {
      id: '/_authenticated/api-playground/'
      path: '/api-playground'
      fullPath: '/api-playground'
      preLoaderRoute: typeof AuthenticatedApiPlaygroundIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-keys/': {
      id: '/_authenticated/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-docs/': {
      id: '/_authenticated/api-docs/'
      path: '/'
      fullPath: '/api-docs/'
      preLoaderRoute: typeof AuthenticatedApiDocsIndexRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/$id': {
      id: '/_authenticated/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AuthenticatedTasksIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills/new': {
      id: '/_authenticated/skills/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof AuthenticatedSkillsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills/$id': {
      id: '/_authenticated/skills/$id'
      path: '/skills/$id'
      fullPath: '/skills/$id'
      preLoaderRoute: typeof AuthenticatedSkillsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$id': {
      id: '/_authenticated/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AuthenticatedSessionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mcp-servers/new': {
      id: '/_authenticated/mcp-servers/new'
      path: '/mcp-servers/new'
      fullPath: '/mcp-servers/new'
      preLoaderRoute: typeof AuthenticatedMcpServersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mcp-servers/$id': {
      id: '/_authenticated/mcp-servers/$id'
      path: '/mcp-servers/$id'
      fullPath: '/mcp-servers/$id'
      preLoaderRoute: typeof AuthenticatedMcpServersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batches/$batchId': {
      id: '/_authenticated/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof AuthenticatedBatchesBatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-docs/upload-file': {
      id: '/_authenticated/api-docs/upload-file'
      path: '/upload-file'
      fullPath: '/api-docs/upload-file'
      preLoaderRoute: typeof AuthenticatedApiDocsUploadFileRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/stream-events': {
      id: '/_authenticated/api-docs/stream-events'
      path: '/stream-events'
      fullPath: '/api-docs/stream-events'
      preLoaderRoute: typeof AuthenticatedApiDocsStreamEventsRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/stream-batch-events': {
      id: '/_authenticated/api-docs/stream-batch-events'
      path: '/stream-batch-events'
      fullPath: '/api-docs/stream-batch-events'
      preLoaderRoute: typeof AuthenticatedApiDocsStreamBatchEventsRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/start-batch': {
      id: '/_authenticated/api-docs/start-batch'
      path: '/start-batch'
      fullPath: '/api-docs/start-batch'
      preLoaderRoute: typeof AuthenticatedApiDocsStartBatchRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/pause-batch': {
      id: '/_authenticated/api-docs/pause-batch'
      path: '/pause-batch'
      fullPath: '/api-docs/pause-batch'
      preLoaderRoute: typeof AuthenticatedApiDocsPauseBatchRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/login': {
      id: '/_authenticated/api-docs/login'
      path: '/login'
      fullPath: '/api-docs/login'
      preLoaderRoute: typeof AuthenticatedApiDocsLoginRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/list-webhooks': {
      id: '/_authenticated/api-docs/list-webhooks'
      path: '/list-webhooks'
      fullPath: '/api-docs/list-webhooks'
      preLoaderRoute: typeof AuthenticatedApiDocsListWebhooksRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/list-files': {
      id: '/_authenticated/api-docs/list-files'
      path: '/list-files'
      fullPath: '/api-docs/list-files'
      preLoaderRoute: typeof AuthenticatedApiDocsListFilesRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/list-batches': {
      id: '/_authenticated/api-docs/list-batches'
      path: '/list-batches'
      fullPath: '/api-docs/list-batches'
      preLoaderRoute: typeof AuthenticatedApiDocsListBatchesRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/list-batch-tasks': {
      id: '/_authenticated/api-docs/list-batch-tasks'
      path: '/list-batch-tasks'
      fullPath: '/api-docs/list-batch-tasks'
      preLoaderRoute: typeof AuthenticatedApiDocsListBatchTasksRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/get-webhook': {
      id: '/_authenticated/api-docs/get-webhook'
      path: '/get-webhook'
      fullPath: '/api-docs/get-webhook'
      preLoaderRoute: typeof AuthenticatedApiDocsGetWebhookRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/get-tasks': {
      id: '/_authenticated/api-docs/get-tasks'
      path: '/get-tasks'
      fullPath: '/api-docs/get-tasks'
      preLoaderRoute: typeof AuthenticatedApiDocsGetTasksRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/get-task': {
      id: '/_authenticated/api-docs/get-task'
      path: '/get-task'
      fullPath: '/api-docs/get-task'
      preLoaderRoute: typeof AuthenticatedApiDocsGetTaskRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/get-file': {
      id: '/_authenticated/api-docs/get-file'
      path: '/get-file'
      fullPath: '/api-docs/get-file'
      preLoaderRoute: typeof AuthenticatedApiDocsGetFileRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/get-batch': {
      id: '/_authenticated/api-docs/get-batch'
      path: '/get-batch'
      fullPath: '/api-docs/get-batch'
      preLoaderRoute: typeof AuthenticatedApiDocsGetBatchRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/download-file': {
      id: '/_authenticated/api-docs/download-file'
      path: '/download-file'
      fullPath: '/api-docs/download-file'
      preLoaderRoute: typeof AuthenticatedApiDocsDownloadFileRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/delete-webhook': {
      id: '/_authenticated/api-docs/delete-webhook'
      path: '/delete-webhook'
      fullPath: '/api-docs/delete-webhook'
      preLoaderRoute: typeof AuthenticatedApiDocsDeleteWebhookRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/delete-file': {
      id: '/_authenticated/api-docs/delete-file'
      path: '/delete-file'
      fullPath: '/api-docs/delete-file'
      preLoaderRoute: typeof AuthenticatedApiDocsDeleteFileRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/delete-batch': {
      id: '/_authenticated/api-docs/delete-batch'
      path: '/delete-batch'
      fullPath: '/api-docs/delete-batch'
      preLoaderRoute: typeof AuthenticatedApiDocsDeleteBatchRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/delete-api-key': {
      id: '/_authenticated/api-docs/delete-api-key'
      path: '/delete-api-key'
      fullPath: '/api-docs/delete-api-key'
      preLoaderRoute: typeof AuthenticatedApiDocsDeleteApiKeyRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/create-webhook': {
      id: '/_authenticated/api-docs/create-webhook'
      path: '/create-webhook'
      fullPath: '/api-docs/create-webhook'
      preLoaderRoute: typeof AuthenticatedApiDocsCreateWebhookRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/create-task': {
      id: '/_authenticated/api-docs/create-task'
      path: '/create-task'
      fullPath: '/api-docs/create-task'
      preLoaderRoute: typeof AuthenticatedApiDocsCreateTaskRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/create-batch': {
      id: '/_authenticated/api-docs/create-batch'
      path: '/create-batch'
      fullPath: '/api-docs/create-batch'
      preLoaderRoute: typeof AuthenticatedApiDocsCreateBatchRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/create-api-key': {
      id: '/_authenticated/api-docs/create-api-key'
      path: '/create-api-key'
      fullPath: '/api-docs/create-api-key'
      preLoaderRoute: typeof AuthenticatedApiDocsCreateApiKeyRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/cancel-task': {
      id: '/_authenticated/api-docs/cancel-task'
      path: '/cancel-task'
      fullPath: '/api-docs/cancel-task'
      preLoaderRoute: typeof AuthenticatedApiDocsCancelTaskRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/cancel-batch': {
      id: '/_authenticated/api-docs/cancel-batch'
      path: '/cancel-batch'
      fullPath: '/api-docs/cancel-batch'
      preLoaderRoute: typeof AuthenticatedApiDocsCancelBatchRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/api-docs/api-keys': {
      id: '/_authenticated/api-docs/api-keys'
      path: '/api-keys'
      fullPath: '/api-docs/api-keys'
      preLoaderRoute: typeof AuthenticatedApiDocsApiKeysRouteImport
      parentRoute: typeof AuthenticatedApiDocsRouteRoute
    }
    '/_authenticated/agents/new': {
      id: '/_authenticated/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthenticatedAgentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/$id': {
      id: '/_authenticated/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AuthenticatedAgentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedApiDocsRouteRouteChildren {
  AuthenticatedApiDocsApiKeysRoute: typeof AuthenticatedApiDocsApiKeysRoute
  AuthenticatedApiDocsCancelBatchRoute: typeof AuthenticatedApiDocsCancelBatchRoute
  AuthenticatedApiDocsCancelTaskRoute: typeof AuthenticatedApiDocsCancelTaskRoute
  AuthenticatedApiDocsCreateApiKeyRoute: typeof AuthenticatedApiDocsCreateApiKeyRoute
  AuthenticatedApiDocsCreateBatchRoute: typeof AuthenticatedApiDocsCreateBatchRoute
  AuthenticatedApiDocsCreateTaskRoute: typeof AuthenticatedApiDocsCreateTaskRoute
  AuthenticatedApiDocsCreateWebhookRoute: typeof AuthenticatedApiDocsCreateWebhookRoute
  AuthenticatedApiDocsDeleteApiKeyRoute: typeof AuthenticatedApiDocsDeleteApiKeyRoute
  AuthenticatedApiDocsDeleteBatchRoute: typeof AuthenticatedApiDocsDeleteBatchRoute
  AuthenticatedApiDocsDeleteFileRoute: typeof AuthenticatedApiDocsDeleteFileRoute
  AuthenticatedApiDocsDeleteWebhookRoute: typeof AuthenticatedApiDocsDeleteWebhookRoute
  AuthenticatedApiDocsDownloadFileRoute: typeof AuthenticatedApiDocsDownloadFileRoute
  AuthenticatedApiDocsGetBatchRoute: typeof AuthenticatedApiDocsGetBatchRoute
  AuthenticatedApiDocsGetFileRoute: typeof AuthenticatedApiDocsGetFileRoute
  AuthenticatedApiDocsGetTaskRoute: typeof AuthenticatedApiDocsGetTaskRoute
  AuthenticatedApiDocsGetTasksRoute: typeof AuthenticatedApiDocsGetTasksRoute
  AuthenticatedApiDocsGetWebhookRoute: typeof AuthenticatedApiDocsGetWebhookRoute
  AuthenticatedApiDocsListBatchTasksRoute: typeof AuthenticatedApiDocsListBatchTasksRoute
  AuthenticatedApiDocsListBatchesRoute: typeof AuthenticatedApiDocsListBatchesRoute
  AuthenticatedApiDocsListFilesRoute: typeof AuthenticatedApiDocsListFilesRoute
  AuthenticatedApiDocsListWebhooksRoute: typeof AuthenticatedApiDocsListWebhooksRoute
  AuthenticatedApiDocsLoginRoute: typeof AuthenticatedApiDocsLoginRoute
  AuthenticatedApiDocsPauseBatchRoute: typeof AuthenticatedApiDocsPauseBatchRoute
  AuthenticatedApiDocsStartBatchRoute: typeof AuthenticatedApiDocsStartBatchRoute
  AuthenticatedApiDocsStreamBatchEventsRoute: typeof AuthenticatedApiDocsStreamBatchEventsRoute
  AuthenticatedApiDocsStreamEventsRoute: typeof AuthenticatedApiDocsStreamEventsRoute
  AuthenticatedApiDocsUploadFileRoute: typeof AuthenticatedApiDocsUploadFileRoute
  AuthenticatedApiDocsIndexRoute: typeof AuthenticatedApiDocsIndexRoute
}

const AuthenticatedApiDocsRouteRouteChildren: AuthenticatedApiDocsRouteRouteChildren =
  {
    AuthenticatedApiDocsApiKeysRoute: AuthenticatedApiDocsApiKeysRoute,
    AuthenticatedApiDocsCancelBatchRoute: AuthenticatedApiDocsCancelBatchRoute,
    AuthenticatedApiDocsCancelTaskRoute: AuthenticatedApiDocsCancelTaskRoute,
    AuthenticatedApiDocsCreateApiKeyRoute:
      AuthenticatedApiDocsCreateApiKeyRoute,
    AuthenticatedApiDocsCreateBatchRoute: AuthenticatedApiDocsCreateBatchRoute,
    AuthenticatedApiDocsCreateTaskRoute: AuthenticatedApiDocsCreateTaskRoute,
    AuthenticatedApiDocsCreateWebhookRoute:
      AuthenticatedApiDocsCreateWebhookRoute,
    AuthenticatedApiDocsDeleteApiKeyRoute:
      AuthenticatedApiDocsDeleteApiKeyRoute,
    AuthenticatedApiDocsDeleteBatchRoute: AuthenticatedApiDocsDeleteBatchRoute,
    AuthenticatedApiDocsDeleteFileRoute: AuthenticatedApiDocsDeleteFileRoute,
    AuthenticatedApiDocsDeleteWebhookRoute:
      AuthenticatedApiDocsDeleteWebhookRoute,
    AuthenticatedApiDocsDownloadFileRoute:
      AuthenticatedApiDocsDownloadFileRoute,
    AuthenticatedApiDocsGetBatchRoute: AuthenticatedApiDocsGetBatchRoute,
    AuthenticatedApiDocsGetFileRoute: AuthenticatedApiDocsGetFileRoute,
    AuthenticatedApiDocsGetTaskRoute: AuthenticatedApiDocsGetTaskRoute,
    AuthenticatedApiDocsGetTasksRoute: AuthenticatedApiDocsGetTasksRoute,
    AuthenticatedApiDocsGetWebhookRoute: AuthenticatedApiDocsGetWebhookRoute,
    AuthenticatedApiDocsListBatchTasksRoute:
      AuthenticatedApiDocsListBatchTasksRoute,
    AuthenticatedApiDocsListBatchesRoute: AuthenticatedApiDocsListBatchesRoute,
    AuthenticatedApiDocsListFilesRoute: AuthenticatedApiDocsListFilesRoute,
    AuthenticatedApiDocsListWebhooksRoute:
      AuthenticatedApiDocsListWebhooksRoute,
    AuthenticatedApiDocsLoginRoute: AuthenticatedApiDocsLoginRoute,
    AuthenticatedApiDocsPauseBatchRoute: AuthenticatedApiDocsPauseBatchRoute,
    AuthenticatedApiDocsStartBatchRoute: AuthenticatedApiDocsStartBatchRoute,
    AuthenticatedApiDocsStreamBatchEventsRoute:
      AuthenticatedApiDocsStreamBatchEventsRoute,
    AuthenticatedApiDocsStreamEventsRoute:
      AuthenticatedApiDocsStreamEventsRoute,
    AuthenticatedApiDocsUploadFileRoute: AuthenticatedApiDocsUploadFileRoute,
    AuthenticatedApiDocsIndexRoute: AuthenticatedApiDocsIndexRoute,
  }

const AuthenticatedApiDocsRouteRouteWithChildren =
  AuthenticatedApiDocsRouteRoute._addFileChildren(
    AuthenticatedApiDocsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApiDocsRouteRoute: typeof AuthenticatedApiDocsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAgentsIdRoute: typeof AuthenticatedAgentsIdRoute
  AuthenticatedAgentsNewRoute: typeof AuthenticatedAgentsNewRoute
  AuthenticatedBatchesBatchIdRoute: typeof AuthenticatedBatchesBatchIdRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedMcpServersIdRoute: typeof AuthenticatedMcpServersIdRoute
  AuthenticatedMcpServersNewRoute: typeof AuthenticatedMcpServersNewRoute
  AuthenticatedSessionsIdRoute: typeof AuthenticatedSessionsIdRoute
  AuthenticatedSkillsIdRoute: typeof AuthenticatedSkillsIdRoute
  AuthenticatedSkillsNewRoute: typeof AuthenticatedSkillsNewRoute
  AuthenticatedTasksIdRoute: typeof AuthenticatedTasksIdRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
  AuthenticatedApiKeysIndexRoute: typeof AuthenticatedApiKeysIndexRoute
  AuthenticatedApiPlaygroundIndexRoute: typeof AuthenticatedApiPlaygroundIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedBatchesIndexRoute: typeof AuthenticatedBatchesIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCommandCenterIndexRoute: typeof AuthenticatedCommandCenterIndexRoute
  AuthenticatedDemoIndexRoute: typeof AuthenticatedDemoIndexRoute
  AuthenticatedFilesIndexRoute: typeof AuthenticatedFilesIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
  AuthenticatedImagesIndexRoute: typeof AuthenticatedImagesIndexRoute
  AuthenticatedMcpServersIndexRoute: typeof AuthenticatedMcpServersIndexRoute
  AuthenticatedMonitoringIndexRoute: typeof AuthenticatedMonitoringIndexRoute
  AuthenticatedProvidersIndexRoute: typeof AuthenticatedProvidersIndexRoute
  AuthenticatedRuntimesIndexRoute: typeof AuthenticatedRuntimesIndexRoute
  AuthenticatedSessionsIndexRoute: typeof AuthenticatedSessionsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSkillStoreIndexRoute: typeof AuthenticatedSkillStoreIndexRoute
  AuthenticatedSkillsIndexRoute: typeof AuthenticatedSkillsIndexRoute
  AuthenticatedSystemIndexRoute: typeof AuthenticatedSystemIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWebhooksIndexRoute: typeof AuthenticatedWebhooksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApiDocsRouteRoute: AuthenticatedApiDocsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAgentsIdRoute: AuthenticatedAgentsIdRoute,
  AuthenticatedAgentsNewRoute: AuthenticatedAgentsNewRoute,
  AuthenticatedBatchesBatchIdRoute: AuthenticatedBatchesBatchIdRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedMcpServersIdRoute: AuthenticatedMcpServersIdRoute,
  AuthenticatedMcpServersNewRoute: AuthenticatedMcpServersNewRoute,
  AuthenticatedSessionsIdRoute: AuthenticatedSessionsIdRoute,
  AuthenticatedSkillsIdRoute: AuthenticatedSkillsIdRoute,
  AuthenticatedSkillsNewRoute: AuthenticatedSkillsNewRoute,
  AuthenticatedTasksIdRoute: AuthenticatedTasksIdRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
  AuthenticatedApiKeysIndexRoute: AuthenticatedApiKeysIndexRoute,
  AuthenticatedApiPlaygroundIndexRoute: AuthenticatedApiPlaygroundIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedBatchesIndexRoute: AuthenticatedBatchesIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCommandCenterIndexRoute: AuthenticatedCommandCenterIndexRoute,
  AuthenticatedDemoIndexRoute: AuthenticatedDemoIndexRoute,
  AuthenticatedFilesIndexRoute: AuthenticatedFilesIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
  AuthenticatedImagesIndexRoute: AuthenticatedImagesIndexRoute,
  AuthenticatedMcpServersIndexRoute: AuthenticatedMcpServersIndexRoute,
  AuthenticatedMonitoringIndexRoute: AuthenticatedMonitoringIndexRoute,
  AuthenticatedProvidersIndexRoute: AuthenticatedProvidersIndexRoute,
  AuthenticatedRuntimesIndexRoute: AuthenticatedRuntimesIndexRoute,
  AuthenticatedSessionsIndexRoute: AuthenticatedSessionsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSkillStoreIndexRoute: AuthenticatedSkillStoreIndexRoute,
  AuthenticatedSkillsIndexRoute: AuthenticatedSkillsIndexRoute,
  AuthenticatedSystemIndexRoute: AuthenticatedSystemIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWebhooksIndexRoute: AuthenticatedWebhooksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
